# Form implementation generated from reading ui file '.\screens\BuySell.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogBuySell(object):
    def setupUi(self, DialogBuySell):
        DialogBuySell.setObjectName("DialogBuySell")
        DialogBuySell.resize(463, 383)
        DialogBuySell.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b; /* gris oscuro */\n"
"    color: #ffffff; /* texto por defecto */\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 14px;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=DialogBuySell)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 60, 250, 238))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbSelectCurrencyOrigin = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.cbSelectCurrencyOrigin.setObjectName("cbSelectCurrencyOrigin")
        self.horizontalLayout.addWidget(self.cbSelectCurrencyOrigin)
        self.lblSelectCurrency_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSelectCurrency_2.sizePolicy().hasHeightForWidth())
        self.lblSelectCurrency_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.lblSelectCurrency_2.setFont(font)
        self.lblSelectCurrency_2.setObjectName("lblSelectCurrency_2")
        self.horizontalLayout.addWidget(self.lblSelectCurrency_2)
        self.cbSelectCurrencyDestination = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.cbSelectCurrencyDestination.setObjectName("cbSelectCurrencyDestination")
        self.horizontalLayout.addWidget(self.cbSelectCurrencyDestination)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblInsertAmount = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInsertAmount.sizePolicy().hasHeightForWidth())
        self.lblInsertAmount.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.lblInsertAmount.setFont(font)
        self.lblInsertAmount.setObjectName("lblInsertAmount")
        self.horizontalLayout_2.addWidget(self.lblInsertAmount)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.txtBuySellAmount = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtBuySellAmount.setObjectName("txtBuySellAmount")
        self.verticalLayout_2.addWidget(self.txtBuySellAmount)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnConfirmTransaction = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConfirmTransaction.sizePolicy().hasHeightForWidth())
        self.btnConfirmTransaction.setSizePolicy(sizePolicy)
        self.btnConfirmTransaction.setStyleSheet("QPushButton {\n"
"    background-color: #4a4a4a; /* gris medio */\n"
"    color: #ffffff;\n"
"    border: 1px solid #666666;\n"
"    border-radius: 5px;\n"
"    padding: 6px 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #777777;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3a3a3a;\n"
"    border: 1px solid #555555;\n"
"}")
        self.btnConfirmTransaction.setObjectName("btnConfirmTransaction")
        self.horizontalLayout_4.addWidget(self.btnConfirmTransaction)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.labelStatusBuySell = QtWidgets.QLabel(parent=DialogBuySell)
        self.labelStatusBuySell.setEnabled(True)
        self.labelStatusBuySell.setGeometry(QtCore.QRect(110, 290, 251, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.labelStatusBuySell.sizePolicy().hasHeightForWidth())
        self.labelStatusBuySell.setSizePolicy(sizePolicy)
        self.labelStatusBuySell.setStyleSheet("QLabel {\n"
"    color: #ff4d4d;           /* rojo fuerte */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.labelStatusBuySell.setText("")
        self.labelStatusBuySell.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelStatusBuySell.setWordWrap(True)
        self.labelStatusBuySell.setObjectName("labelStatusBuySell")
        self.lblBuySell_2 = QtWidgets.QLabel(parent=DialogBuySell)
        self.lblBuySell_2.setGeometry(QtCore.QRect(110, 40, 46, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBuySell_2.sizePolicy().hasHeightForWidth())
        self.lblBuySell_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.lblBuySell_2.setFont(font)
        self.lblBuySell_2.setObjectName("lblBuySell_2")
        self.lblBuySell = QtWidgets.QLabel(parent=DialogBuySell)
        self.lblBuySell.setGeometry(QtCore.QRect(250, 40, 50, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBuySell.sizePolicy().hasHeightForWidth())
        self.lblBuySell.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.lblBuySell.setFont(font)
        self.lblBuySell.setObjectName("lblBuySell")

        self.retranslateUi(DialogBuySell)
        QtCore.QMetaObject.connectSlotsByName(DialogBuySell)

    def retranslateUi(self, DialogBuySell):
        _translate = QtCore.QCoreApplication.translate
        DialogBuySell.setWindowTitle(_translate("DialogBuySell", "Comprar o vender"))
        self.lblSelectCurrency_2.setText(_translate("DialogBuySell", "->"))
        self.lblInsertAmount.setText(_translate("DialogBuySell", "Ingrese la cantidad:"))
        self.btnConfirmTransaction.setText(_translate("DialogBuySell", "Confirmar transacción"))
        self.lblBuySell_2.setText(_translate("DialogBuySell", "Origen"))
        self.lblBuySell.setText(_translate("DialogBuySell", "Destino"))
