# Form implementation generated from reading ui file '.\screens\createAccount.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogCreateAccount(object):
    def setupUi(self, DialogCreateAccount):
        DialogCreateAccount.setObjectName("DialogCreateAccount")
        DialogCreateAccount.resize(471, 329)
        DialogCreateAccount.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b; /* gris oscuro */\n"
"    color: #ffffff; /* texto por defecto */\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=DialogCreateAccount)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 60, 211, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblSelectCurrencyCreate = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSelectCurrencyCreate.sizePolicy().hasHeightForWidth())
        self.lblSelectCurrencyCreate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.lblSelectCurrencyCreate.setFont(font)
        self.lblSelectCurrencyCreate.setObjectName("lblSelectCurrencyCreate")
        self.horizontalLayout_3.addWidget(self.lblSelectCurrencyCreate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.cbSelectCurrencyCreate = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.cbSelectCurrencyCreate.setObjectName("cbSelectCurrencyCreate")
        self.verticalLayout_2.addWidget(self.cbSelectCurrencyCreate)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnCreateAccount = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCreateAccount.sizePolicy().hasHeightForWidth())
        self.btnCreateAccount.setSizePolicy(sizePolicy)
        self.btnCreateAccount.setStyleSheet("QPushButton {\n"
"    background-color: #4a4a4a; /* gris medio */\n"
"    color: #ffffff;\n"
"    border: 1px solid #666666;\n"
"    border-radius: 5px;\n"
"    padding: 6px 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #777777;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3a3a3a;\n"
"    border: 1px solid #555555;\n"
"}")
        self.btnCreateAccount.setObjectName("btnCreateAccount")
        self.horizontalLayout_4.addWidget(self.btnCreateAccount)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(DialogCreateAccount)
        QtCore.QMetaObject.connectSlotsByName(DialogCreateAccount)

    def retranslateUi(self, DialogCreateAccount):
        _translate = QtCore.QCoreApplication.translate
        DialogCreateAccount.setWindowTitle(_translate("DialogCreateAccount", "Dialog"))
        self.lblSelectCurrencyCreate.setText(_translate("DialogCreateAccount", "Seleccione la cuenta a crear: "))
        self.btnCreateAccount.setText(_translate("DialogCreateAccount", "Crear cuenta"))
