# Form implementation generated from reading ui file '.\screens\deposit.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogDeposit(object):
    def setupUi(self, DialogDeposit):
        DialogDeposit.setObjectName("DialogDeposit")
        DialogDeposit.resize(461, 383)
        DialogDeposit.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b; /* gris oscuro */\n"
"    color: #ffffff; /* texto por defecto */\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 14px;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=DialogDeposit)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 30, 216, 238))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblSelectCurrency = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSelectCurrency.sizePolicy().hasHeightForWidth())
        self.lblSelectCurrency.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.lblSelectCurrency.setFont(font)
        self.lblSelectCurrency.setObjectName("lblSelectCurrency")
        self.horizontalLayout_3.addWidget(self.lblSelectCurrency)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.cbSelectCurrencyDeposit = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.cbSelectCurrencyDeposit.setObjectName("cbSelectCurrencyDeposit")
        self.cbSelectCurrencyDeposit.addItem("")
        self.verticalLayout_2.addWidget(self.cbSelectCurrencyDeposit)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblDepositArsAmount = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDepositArsAmount.sizePolicy().hasHeightForWidth())
        self.lblDepositArsAmount.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.lblDepositArsAmount.setFont(font)
        self.lblDepositArsAmount.setObjectName("lblDepositArsAmount")
        self.horizontalLayout_2.addWidget(self.lblDepositArsAmount)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.txtDepositArsAmount = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtDepositArsAmount.setObjectName("txtDepositArsAmount")
        self.verticalLayout_2.addWidget(self.txtDepositArsAmount)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnDeposit = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeposit.sizePolicy().hasHeightForWidth())
        self.btnDeposit.setSizePolicy(sizePolicy)
        self.btnDeposit.setStyleSheet("QPushButton {\n"
"    background-color: #4a4a4a; /* gris medio */\n"
"    color: #ffffff;\n"
"    border: 1px solid #666666;\n"
"    border-radius: 5px;\n"
"    padding: 6px 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #777777;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3a3a3a;\n"
"    border: 1px solid #555555;\n"
"}")
        self.btnDeposit.setObjectName("btnDeposit")
        self.horizontalLayout_4.addWidget(self.btnDeposit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.labelStatusDeposit = QtWidgets.QLabel(parent=DialogDeposit)
        self.labelStatusDeposit.setEnabled(True)
        self.labelStatusDeposit.setGeometry(QtCore.QRect(120, 280, 241, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.labelStatusDeposit.sizePolicy().hasHeightForWidth())
        self.labelStatusDeposit.setSizePolicy(sizePolicy)
        self.labelStatusDeposit.setStyleSheet("QLabel {\n"
"    color: #ff4d4d;           /* rojo fuerte */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.labelStatusDeposit.setText("")
        self.labelStatusDeposit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelStatusDeposit.setWordWrap(True)
        self.labelStatusDeposit.setObjectName("labelStatusDeposit")

        self.retranslateUi(DialogDeposit)
        QtCore.QMetaObject.connectSlotsByName(DialogDeposit)

    def retranslateUi(self, DialogDeposit):
        _translate = QtCore.QCoreApplication.translate
        DialogDeposit.setWindowTitle(_translate("DialogDeposit", "Depositar"))
        self.lblSelectCurrency.setText(_translate("DialogDeposit", "Seleccione una moneda: "))
        self.cbSelectCurrencyDeposit.setItemText(0, _translate("DialogDeposit", "ARS"))
        self.lblDepositArsAmount.setText(_translate("DialogDeposit", "Ingrese la cantidad a depositar:"))
        self.btnDeposit.setText(_translate("DialogDeposit", "Depositar"))
