# Form implementation generated from reading ui file 'screens/login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogLogin(object):
    def setupUi(self, DialogLogin):
        DialogLogin.setObjectName("DialogLogin")
        DialogLogin.resize(800, 600)
        DialogLogin.setMinimumSize(QtCore.QSize(50, 50))
        DialogLogin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        DialogLogin.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        DialogLogin.setStyleSheet("QDialog, QWidget {\n"
"    background-color: #2b2b2b; /* gris oscuro */\n"
"    color: #ffffff; /* texto por defecto */\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 14px;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=DialogLogin)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 130, 332, 324))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(30, 0, 30, 10)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: #e0e0e0; /* gris claro para texto */\n"
"    font-size: 14px;\n"
"}")
        self.label_3.setLineWidth(1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditUsername.sizePolicy().hasHeightForWidth())
        self.lineEditUsername.setSizePolicy(sizePolicy)
        self.lineEditUsername.setStyleSheet("QLineEdit {\n"
"    background-color: #3a3a3a; /* gris medio */\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    color: #ffffff; /* texto que escribís */\n"
"    selection-background-color: #5a5a5a;\n"
"}\n"
"\n"
"/* Placeholder */\n"
"QLineEdit:placeholder {\n"
"    color: #aaaaaa; /* gris más claro */\n"
"}\n"
"")
        self.lineEditUsername.setText("")
        self.lineEditUsername.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.verticalLayout_2.addWidget(self.lineEditUsername)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    background-color: #3a3a3a; /* gris medio */\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    color: #ffffff; /* texto que escribís */\n"
"    selection-background-color: #5a5a5a;\n"
"}\n"
"\n"
"/* Placeholder */\n"
"QLineEdit:placeholder {\n"
"    color: #aaaaaa; /* gris más claro */\n"
"}\n"
"")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_2.addWidget(self.lineEditPassword)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLogin = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLogin.sizePolicy().hasHeightForWidth())
        self.btnLogin.setSizePolicy(sizePolicy)
        self.btnLogin.setMinimumSize(QtCore.QSize(0, 0))
        self.btnLogin.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnLogin.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.btnLogin.setStyleSheet("QPushButton {\n"
"    background-color: #4a4a4a; /* gris medio */\n"
"    color: #ffffff;\n"
"    border: 1px solid #666666;\n"
"    border-radius: 5px;\n"
"    padding: 6px 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #777777;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3a3a3a;\n"
"    border: 1px solid #555555;\n"
"}")
        self.btnLogin.setObjectName("btnLogin")
        self.horizontalLayout.addWidget(self.btnLogin)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelStatusLogin = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.labelStatusLogin.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.labelStatusLogin.sizePolicy().hasHeightForWidth())
        self.labelStatusLogin.setSizePolicy(sizePolicy)
        self.labelStatusLogin.setStyleSheet("QLabel {\n"
"    color: #ff4d4d;           /* rojo fuerte */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.labelStatusLogin.setText("")
        self.labelStatusLogin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelStatusLogin.setWordWrap(True)
        self.labelStatusLogin.setObjectName("labelStatusLogin")
        self.horizontalLayout_4.addWidget(self.labelStatusLogin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(50, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnRegister = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRegister.sizePolicy().hasHeightForWidth())
        self.btnRegister.setSizePolicy(sizePolicy)
        self.btnRegister.setStyleSheet("QPushButton {\n"
"    background-color: #4a4a4a; /* gris medio */\n"
"    color: #ffffff;\n"
"    border: 1px solid #666666;\n"
"    border-radius: 5px;\n"
"    padding: 6px 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #777777;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3a3a3a;\n"
"    border: 1px solid #555555;\n"
"}")
        self.btnRegister.setDefault(False)
        self.btnRegister.setObjectName("btnRegister")
        self.horizontalLayout_2.addWidget(self.btnRegister)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DialogLogin)
        QtCore.QMetaObject.connectSlotsByName(DialogLogin)

    def retranslateUi(self, DialogLogin):
        _translate = QtCore.QCoreApplication.translate
        DialogLogin.setWindowTitle(_translate("DialogLogin", "Dialog"))
        self.label_3.setText(_translate("DialogLogin", "Usuario"))
        self.label_2.setText(_translate("DialogLogin", "Contraseña"))
        self.btnLogin.setText(_translate("DialogLogin", "Acceder"))
        self.label.setText(_translate("DialogLogin", "¿No tenés una cuenta? Registrate"))
        self.btnRegister.setText(_translate("DialogLogin", "Registrarse"))
