# Form implementation generated from reading ui file '.\screens\register.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogRegister(object):
    def setupUi(self, DialogRegister):
        DialogRegister.setObjectName("DialogRegister")
        DialogRegister.resize(800, 600)
        DialogRegister.setStyleSheet("QDialog, QWidget {\n"
"    background-color: #2b2b2b; /* gris oscuro */\n"
"    color: #ffffff; /* texto por defecto */\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 14px;\n"
"}")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=DialogRegister)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(230, 110, 332, 328))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(30, 0, 30, 10)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblLoginTitle = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLoginTitle.sizePolicy().hasHeightForWidth())
        self.lblLoginTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.lblLoginTitle.setFont(font)
        self.lblLoginTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLoginTitle.setObjectName("lblLoginTitle")
        self.horizontalLayout_7.addWidget(self.lblLoginTitle)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.lblUserRegister = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.lblUserRegister.setStyleSheet("QLabel {\n"
"    color: #e0e0e0; /* gris claro para texto */\n"
"    font-size: 14px;\n"
"}")
        self.lblUserRegister.setLineWidth(1)
        self.lblUserRegister.setObjectName("lblUserRegister")
        self.verticalLayout_4.addWidget(self.lblUserRegister)
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditUsername.sizePolicy().hasHeightForWidth())
        self.lineEditUsername.setSizePolicy(sizePolicy)
        self.lineEditUsername.setStyleSheet("QLineEdit {\n"
"    background-color: #3a3a3a; /* gris medio */\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    color: #ffffff; /* texto que escribís */\n"
"    selection-background-color: #5a5a5a;\n"
"}\n"
"\n"
"/* Placeholder */\n"
"QLineEdit:placeholder {\n"
"    color: #aaaaaa; /* gris más claro */\n"
"}\n"
"")
        self.lineEditUsername.setText("")
        self.lineEditUsername.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.verticalLayout_4.addWidget(self.lineEditUsername)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.lblPasswordRegister = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.lblPasswordRegister.setObjectName("lblPasswordRegister")
        self.verticalLayout_4.addWidget(self.lblPasswordRegister)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    background-color: #3a3a3a; /* gris medio */\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    color: #ffffff; /* texto que escribís */\n"
"    selection-background-color: #5a5a5a;\n"
"}\n"
"\n"
"/* Placeholder */\n"
"QLineEdit:placeholder {\n"
"    color: #aaaaaa; /* gris más claro */\n"
"}\n"
"")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_4.addWidget(self.lineEditPassword)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.lblConfirmPasswordRegister = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.lblConfirmPasswordRegister.setObjectName("lblConfirmPasswordRegister")
        self.verticalLayout_4.addWidget(self.lblConfirmPasswordRegister)
        self.lineEditPassword2 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.lineEditPassword2.setStyleSheet("QLineEdit {\n"
"    background-color: #3a3a3a; /* gris medio */\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    color: #ffffff; /* texto que escribís */\n"
"    selection-background-color: #5a5a5a;\n"
"}\n"
"\n"
"/* Placeholder */\n"
"QLineEdit:placeholder {\n"
"    color: #aaaaaa; /* gris más claro */\n"
"}\n"
"")
        self.lineEditPassword2.setText("")
        self.lineEditPassword2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword2.setObjectName("lineEditPassword2")
        self.verticalLayout_4.addWidget(self.lineEditPassword2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelStatusRegister = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.labelStatusRegister.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.labelStatusRegister.sizePolicy().hasHeightForWidth())
        self.labelStatusRegister.setSizePolicy(sizePolicy)
        self.labelStatusRegister.setStyleSheet("QLabel {\n"
"    color: #ff4d4d;           /* rojo fuerte */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.labelStatusRegister.setText("")
        self.labelStatusRegister.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelStatusRegister.setWordWrap(True)
        self.labelStatusRegister.setObjectName("labelStatusRegister")
        self.horizontalLayout_6.addWidget(self.labelStatusRegister)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnRegister = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRegister.sizePolicy().hasHeightForWidth())
        self.btnRegister.setSizePolicy(sizePolicy)
        self.btnRegister.setMinimumSize(QtCore.QSize(0, 0))
        self.btnRegister.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnRegister.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.btnRegister.setStyleSheet("QPushButton {\n"
"    background-color: #4a4a4a; /* gris medio */\n"
"    color: #ffffff;\n"
"    border: 1px solid #666666;\n"
"    border-radius: 5px;\n"
"    padding: 6px 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #777777;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3a3a3a;\n"
"    border: 1px solid #555555;\n"
"}")
        self.btnRegister.setObjectName("btnRegister")
        self.horizontalLayout_5.addWidget(self.btnRegister)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.labelStatus = QtWidgets.QLabel(parent=DialogRegister)
        self.labelStatus.setEnabled(True)
        self.labelStatus.setGeometry(QtCore.QRect(500, 380, 0, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setStyleSheet("QLabel {\n"
"    color: #ff4d4d;           /* rojo fuerte */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.labelStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")

        self.retranslateUi(DialogRegister)
        QtCore.QMetaObject.connectSlotsByName(DialogRegister)

    def retranslateUi(self, DialogRegister):
        _translate = QtCore.QCoreApplication.translate
        DialogRegister.setWindowTitle(_translate("DialogRegister", "Dialog"))
        self.lblLoginTitle.setText(_translate("DialogRegister", "Registrarse"))
        self.lblUserRegister.setText(_translate("DialogRegister", "Usuario"))
        self.lblPasswordRegister.setText(_translate("DialogRegister", "Contraseña"))
        self.lblConfirmPasswordRegister.setText(_translate("DialogRegister", "Confirma tu contraseña"))
        self.btnRegister.setText(_translate("DialogRegister", "Registrarse"))
        self.labelStatus.setText(_translate("DialogRegister", "DDDDD"))
